import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import SessionWrapper from "./providers/SessionWrapper";
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700", "900"] });
import "@/app/styles/main.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <SessionWrapper>
    <html lang="en">
      <body className={poppins.className}>
        {children}
      </body>
    </html>
    </SessionWrapper>
  );
}
